export const platinumAppleProbability = [
  { name: "카르마 스타포스 20성 강화권 (200제)", probability: 0.03 },
  { name: "카르마 스타포스 18성 강화권 (250제)", probability: 0.07 },
  { name: "심연의 환생의 불꽃", probability: 5 },
  { name: "펫장비 리턴 스크롤", probability: 1.5 },
  { name: "펫장비 이노센트 주문서 100%", probability: 1.5 },
  { name: "펫장비 순백의 주문서 100%", probability: 2 },
  { name: "놀라운 긍정의 혼돈 주문서 100%", probability: 2 },
  { name: "리턴 스크롤", probability: 3 },
  { name: "매지컬 두손무기 공격력 주문서 50%", probability: 1 },
  { name: "매지컬 한손무기 공격력 주문서 50%", probability: 1 },
  { name: "매지컬 한손무기 마력 주문서 50%", probability: 0.9 },
  { name: "프리미엄 악세서리 공격력 스크롤 50%", probability: 1.5 },
  { name: "프리미엄 펫장비 공격력 스크롤 50%", probability: 3 },
  { name: "프리미엄 악세서리 마력 스크롤 50%", probability: 0.5 },
  { name: "프리미엄 펫장비 마력 스크롤 50%", probability: 1 },
  { name: "경험치 3배 쿠폰 (30분)", probability: 9 },
  { name: "경험치 4배 쿠폰 (30분)", probability: 3 },
  { name: "선택 아케인심볼 교환권 10개", probability: 18 },
  { name: "선택 어센틱심볼 교환권 10개", probability: 18 },
  { name: "희미한 솔 에르다의 기운 10개", probability: 18 },
  { name: "솔 에르다의 기운", probability: 8 },
  { name: "짙은 솔 에르다의 기운", probability: 2 },
];
